c_compiler:                    # [win]
  - vs2019                     # [win]
cxx_compiler:                  # [win]
  - vs2019                     # [win]
libpq:                         # [win]
  - '16'                       # [win]