{% set name = "pgvector" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6ffdd35d2882d18e1d6e68d042105f2c9b8b1e559f1ef8424db1e05aead7cc99

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - perl            # [build_platform == target_platform]
    - gnuconfig       # [unix]
    - postgresql      # [build_platform != target_platform]
    - make            # [unix]
    - m2-patch        # [win]
    - m2-diffutils    # [win]
    - posix           # [win]
  host:
    - postgresql
  run:
    - libpq

test:
  commands:
    - test -f $PREFIX/lib/vector.so                                                     # [unix]
    - test -f $PREFIX/share/extension/vector--{{ version }}.sql                         # [unix]
    - test -f $PREFIX/share/extension/vector.control                                    # [unix]
    - if not exist %LIBRARY_LIB%\vector.dll exit 1                                      # [win]
    - if not exist %LIBRARY_PREFIX%\share\extension\vector--{{ version }}.sql exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\share\extension\vector.control exit 1               # [win]


about:
  home: https://github.com/pgvector/pgvector
  summary: Open-source vector similarity search for Postgres.
  description: Open-source vector similarity search for Postgres.
  license: PostgreSQL
  license_file: LICENSE
  doc_url: https://github.com/pgvector/pgvector
  dev_url: https://github.com/pgvector/pgvector

extra:
  recipe-maintainers:
    - mmcauliffe
