{% set name = "pgvector" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b76cf84ddad452cc880a6c8c661d137ddd8679c000a16332f4f03ecf6e10bcc8
  patches:
    - patches/0002-CMakeLists.patch  # build_platform != target_platform]

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - perl
    - gnuconfig       # [unix]
    - postgresql      # [build_platform != target_platform]
    - libpq           # [build_platform != target_platform]
    - make            # [unix]
    - cmake           # [build_platform != target_platform]
    - m2-patch        # [win]
    - m2-diffutils    # [win]
    - posix           # [win]
  host:
    - postgresql
    - libpq
  run:
    - libpq
    - postgresql

test:
  commands:
      - test -f $PREFIX/lib/vector.so                                                   # [unix]
      - test -f $PREFIX/share/extension/vector--{{ version }}.sql                       # [unix]
      - test -f $PREFIX/share/extension/vector.control                                  # [unix]
      - if not exist %LIBRARY_LIB%\vector.dll exit 1                                    # [win]
      - if not exist %LIBRARY_PREFIX%\share\extension\vector--{{ version }}.sql exit 1  # [win]
      - if not exist %LIBRARY_PREFIX%\share\extension\vector.control exit 1             # [win]


about:
  home: https://github.com/pgvector/pgvector
  summary: Open-source vector similarity search for Postgres.
  description: Open-source vector similarity search for Postgres.
  license: PostgreSQL
  license_file: LICENSE
  doc_url: https://github.com/pgvector/pgvector
  dev_url: https://github.com/pgvector/pgvector

extra:
  recipe-maintainers:
    - mmcauliffe
